name: Zhihu-HotList-Auto

on:
  push:
    branches:
      - main
  schedule: # 定时任务
    - cron: "0 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 代码检查
        uses: actions/checkout@v3
        with:
          ref: main

      - name: 安装Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: 安装依赖, 爬取知乎热榜
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install httpx[http2]
          python3 main.py

      - name: 读取当前提交名
        id: name
        uses: ashley-taylor/read-json-property-action@v1.0
        with:
          path: ./package.json
          property: name

      - name: 读取当前版本号
        id: tag
        uses: ashley-taylor/read-json-property-action@v1.0
        with:
          path: ./package.json
          property: tag

      - name: 创建构建
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.value }}
          name: ${{ steps.name.outputs.value }}
          body: 知乎热榜
          token: ${{ secrets.ACCESS_TOKEN }}
          draft: false
          prerelease: false
          files: |
            Zhihu-HotList.json
            LICENSE
